SINGLE = 'Single'
SHARED = 'Shared'
ACCOMODATIONS = (
    (SINGLE, 'Single'),
    (SHARED, 'Shared'),
)
PARISHES = (
    ('ST.THOMAS', 'ST.THOMAS'),
    ('KINGSTON', 'KINGSTON'),
    ('CLARENDON', 'CLARENDON'),
    ('MANCHESTER', 'MANCHESTER'),
    ('STMARY', 'STMARY'),
    ('STANN', 'STANN'),
    ('PORTLAND', 'PORTLAND'),
    ('WESTMORELAND', 'WESTMORELAND'),
    ('ST.ELIZABETH', 'ST.ELIZABETH'),
    ('HANOVER', 'HANOVER'),
    ('ST.ANDREW', 'ST.ANDREW'),
    ('TRELAWNY', 'TRELAWNY'),
    ('ST.JAMES', 'ST.JAMES'),
    ('ST.CATHERINE', 'ST.CATHERINE'),
)
DEFAULT_PARISH = 'kINGSTON'
